const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  theme: {
    borderRadius: {
      none: '0px' /* 0px */,
      sm: '0.25rem' /* 4px */,
      md: '0.5rem' /* 8px */,
      lg: '1rem' /* 16px */,
      full: '9999rem',
    },
    colors: {
      transparent: 'rgba(0, 0, 0, 0)',
      white: '#fff',
      black: 'var(--color-black)',
      gray: {
        DEFAULT: 'var(--color-gray-base)',
        muted: 'var(--color-gray-muted)',
        lightest: 'var(--color-gray-lightest)',
        lighter: 'var(--color-gray-lighter)',
        light: 'var(--color-gray-light)',
        base: 'var(--color-gray-base)',
        dark: 'var(--color-gray-dark)',
        darker: 'var(--color-gray-darker)',
        darkest: 'var(--color-gray-darkest)',
      },
      primary: {
        DEFAULT: 'var(--color-primary-base)',
        muted: 'var(--color-primary-muted)',
        light: 'var(--color-primary-light)',
        base: 'var(--color-primary-base)',
        dark: 'var(--color-primary-dark)',
      },
      secondary: {
        DEFAULT: 'var(--color-secondary-base)',
        muted: 'var(--color-secondary-muted)',
        light: 'var(--color-secondary-light)',
        base: 'var(--color-secondary-base)',
        dark: 'var(--color-secondary-dark)',
      },
      info: {
        DEFAULT: 'var(--color-info-base)',
        muted: 'var(--color-info-muted)',
        light: 'var(--color-info-light)',
        base: 'var(--color-info-base)',
        dark: 'var(--color-info-dark)',
      },
      success: {
        DEFAULT: 'var(--color-success-base)',
        muted: 'var(--color-success-muted)',
        light: 'var(--color-success-light)',
        base: 'var(--color-success-base)',
        dark: 'var(--color-success-dark)',
      },
      danger: {
        DEFAULT: 'var(--color-danger-base)',
        muted: 'var(--color-danger-muted)',
        light: 'var(--color-danger-light)',
        base: 'var(--color-danger-base)',
        dark: 'var(--color-danger-dark)',
      },
      warning: {
        DEFAULT: 'var(--color-warning-base)',
        muted: 'var(--color-warning-muted)',
        light: 'var(--color-warning-light)',
        base: 'var(--color-warning-base)',
        dark: 'var(--color-warning-dark)',
      },
    },
    fontFamily: {
      sans: ['var(--font-sans)', ...defaultTheme.fontFamily.sans],
      serif: ['var(--font-sans-serif)', ...defaultTheme.fontFamily.serif],
    },
    fontSize: {
      xs: ['0.75rem' /* 12px */, '1rem' /* 16px */],
      sm: ['0.875rem' /* 14px */, '1.25rem' /* 20px */],
      md: ['1rem' /* 16px */, '1.5rem' /* 24px */],
      lg: ['1.125rem' /* 18px */, '1.75rem' /* 28px */],
      xl: ['1.25rem' /* 20px */, '1.75rem' /* 28px */],
      '2xl': ['1.5rem' /* 24px */, '2rem' /* 32px */],
      '3xl': ['1.875rem' /* 30px */, '2.25rem' /* 36px */],
      // '4xl': [
      //   '2.25rem', /* 36px */
      //   '2.5rem', /* 40px */
      // ],
      // '5xl': ['3rem', '1'], /* 48px */
      // '6xl': ['3.75rem', '1'], /* 60px */
      // '7xl': ['4.5rem', '1'], /* 72px */
      // '8xl': ['6rem', '1'], /* 96px */
      // '9xl': ['8rem', '1'], /* 128px */
    },
    fontWeight: {
      // thin: '100',
      // extralight: '200',
      // light: '300',
      normal: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
      // extrabold: '800',
      // black: '900',
    },
    screens: {
      // Extra small screen / phone
      xs: '0px',
      // Small screen / phone
      sm: '421px',
      // Medium screen / tablet
      md: '641px',
      // Large screen / desktop
      lg: '789px',
      // Extra large screen / wide desktop
      xl: '1367px',
      '2xl': '1921px',
    },
    spacing: {
      0: '0rem' /* 0px */,
      px: '0.0625rem' /* 1px */,
      0.5: '0.125rem' /* 2px */,
      1: '0.25rem' /* 4px */,
      1.5: '0.375rem' /* 6px */,
      2: '0.5rem' /* 8px */,
      2.5: '0.625rem' /* 10px */,
      3: '0.75rem' /* 12px */,
      3.5: '0.875rem' /* 14px */,
      4: '1rem' /* 16px */,
      5: '1.25rem' /* 20px */,
      6: '1.5rem' /* 24px */,
      7: '1.75rem' /* 28px */,
      8: '2rem' /* 32px */,
      9: '2.25rem' /* 36px */,
      10: '2.5rem' /* 40px */,
      11: '2.75rem' /* 44px */,
      12: '3rem' /* 48px */,
      14: '3.5rem' /* 56px */,
      16: '4rem' /* 64px */,
      20: '5rem' /* 80px */,
      24: '6rem' /* 96px */,
      28: '7rem' /* 112px */,
      32: '8rem' /* 128px */,
      36: '9rem' /* 144px */,
      40: '10rem' /* 160px */,
      44: '11rem' /* 176px */,
      48: '12rem' /* 192px */,
      52: '13rem' /* 208px */,
      56: '14rem' /* 224px */,
      60: '15rem' /* 240px */,
      64: '16rem' /* 256px */,
      72: '18rem' /* 288px */,
      80: '20rem' /* 320px */,
      96: '24rem' /* 384px */,
      auto: 'auto',
      '1/2': '50%',
      '1/3': '33.333333%',
      '2/3': '66.666667%',
      '1/4': '25%',
      '2/4': '50%',
      '3/4': '75%',
      '1/5': '20%',
      '2/5': '40%',
      '3/5': '60%',
      '4/5': '80%',
      '1/6': '16.666667%',
      '2/6': '33.333333%',
      '3/6': '50%',
      '4/6': '66.666667%',
      '5/6': '83.333333%',
      full: '100%',
      screen: '100vh',
      min: 'min-content',
      max: 'max-content',
      fit: 'fit-content',
    },
    boxShadow: {
      focus: '0 0 0 3px rgba(45, 128, 255, 0.8)',
      'button-focus': '0 0 0 3px rgba(45, 128, 255, 0.8)',
      'button-shadow': '0 0 0 2px var(--color-outline-light), 0 0 4px 0 rgba(0, 0, 0, 0.25)',
      'button-inner': 'inset 0 0 8px 6px rgb(0 0 0 / .05)',
      'input-focus': '0 0 0 3px var(--color-primary)',
    },
  },
  plugins: [],
  corePlugins: {
    preflight: false,
  },
};
